spring:
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/bank_microservice_db
      username: postgres
      password: postgres
      liquibase:
        change-log: classpath:/db/changelog/db.changelog-postgres.yaml
        drop-first: true
        enabled: true
    cassandra:
      driver-class-name: com.simba.cassandra.jdbc42.Driver
      jdbcUrl: jdbc:cassandra://127.0.0.1:9042/my_keyspace;DefaultKeyspace=my_keyspace
      username: shukyurov
      password: cassandra
      liquibase:
        change-log: classpath:/db/changelog/db.changelog-cassandra.yaml
#        enabled: true
#        drop-first: true
#        clear-checksums: true

  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: my_keyspace
      local-datacenter: datacenter1
#  datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/bank_microservice_db
#      username: postgres
#      password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



